# Generated by Django 2.2.24 on 2022-02-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0003_auto_20210823_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.TextField()),
            ],
            options={
                'verbose_name': 'LogoSetting',
                'verbose_name_plural': 'LogoSetting',
            },
        ),
    ]
